# Generated by Django 4.2.4 on 2023-08-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('icon', models.CharField(choices=[('lni-rocket', 'Rocket'), ('lni-laptop-phone', 'Laptop-Phone'), ('lni-cog', 'gear'), ('lni-leaf', 'Leaf'), ('lni-layers', 'Layers')], max_length=18)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
